### ISSUE TITLE
suggestion: use a platform-agnostic filter via HTTP adapter abstraction

### ISSUE THREAD

**Issue by micalevisk** [Fcmam5/nest-http-problem-details#7]
hi! good lib!

as of now, due to the usage of `response.type`,`response.send` and so on, this exception filter only works for http adapters that implements such methods on their response object. Express and Fastify has them but 3rd-party http adapters might not have (because they aren't needed for nestjs core AFIAK)

https://github.com/Fcmam5/nest-problem-details/blob/43ad7c9410c6c240e307abde249ae7ff2c38d12f/libs/nest-problem-details-filter/src/filters/http-exception.filter.ts#L55-L66

My suggestion is using the `HttpAdapterHost` instead like the docs shows here: https://docs.nestjs.com/exception-filters#catch-everything

at same time, as we need to inject that dependency into the `HttpExceptionFilter`, there's no way to add this feature without introducing a breaking change because now one will need to supply that new parameter when using the `app.useGlobalFilters` bind approach (like described [here](https://docs.nestjs.com/faq/http-adapter))

so yeah, it's up to you :smile: 

btw I'd like to contribute to this project because of Hacktoberfest :p

**Comment by Fcmam5** [comment]
Brilliant! Yes please go ahead and fix it.

Thank you very much for the references!
